# Generated by Django 5.1.4 on 2025-01-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Web Developer', max_length=100)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('degree', models.CharField(max_length=100)),
                ('freelance', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50)),
                ('description_short', models.TextField(help_text="Short description for the 'About' section")),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
            ],
        ),
    ]
