# Generated by Django 5.1.4 on 2025-01-04 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='class_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
