# Generated by Django 5.1.4 on 2025-01-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_education_created_at_alter_education_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
