# Generated by Django 5.1.4 on 2025-01-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_alter_education_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('skill_img', models.ImageField(upload_to='skills_images/')),
            ],
        ),
    ]
