# Generated by Django 5.1.4 on 2025-01-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='certificates/')),
            ],
        ),
    ]
