# Generated by Django 5.1.4 on 2025-01-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0006_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(default=1, help_text='Short description for the about the certificate section'),
            preserve_default=False,
        ),
    ]
