# Generated by Django 5.1.3 on 2025-01-08 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0010_alter_project_thumbnail_alter_projectimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_date',
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
